### ISSUE TITLE
Multiple assets in multiple plant_locations cause duplication of `id_loan` causing `summarize_*_production()` to err

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#106]
From an e-mail conversation with @QianFeng2020:
> There is a setup in the tool that does not fit the real global dataset well. In the global data set, there are some companies that holds assets in different locations/ technology. When the tool joins the matched loan book with the global datasets, it includes all combinations of this one company and all of relevant locations/technology for the same loan. In this case, there would be duplicated id_loan in the outcome “loanbook_joined_to_ald_scenario”. It will cause and error in the following function “summarize_portfolio_production”, which requires that one “id_loan” has only one exposure value.
The example in the snapshot above can illustrate this problem too. In the snapshop you can see that this company has assets with technology “HydroCap” and “RenewablesCap” in “ES”, and also one technology “RenewablesCaps” in different locations. It will finally results in duplicated “id_loan” in the outcome “loanbook_joined_to_ald_scenario”.

**Comment by jdhoffa** [comment]
@QianFeng2020 I am unable to reproduce the error you describe. 
I have made a very small mock example, with a single loan to a company that maps to assets (hydro and renewables) in multiple countries (ES and KZ) and multiple regions (europe and caspian). While the id_loan does duplicate, the internal grouping ensures that for every group, the id's are unique. 

Can you inspect the following reprex, and see what I am missing (you can just copy the bulk of that code into R and run it and inspect the objects there if it's easier)? Once I can reproduce the error we can try to fix it:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)

data <- tibble::tribble(
  ~id_loan, ~loan_size_outstanding, ~loan_size_credit_limit, ~id_2dii,            ~level, ~score, ~sector,         ~name_ald, ~sector_ald,
      "L1",                     1L,                      2L,    "UP1", "ultimate_parent",     1L, "power", "a power company",     "power"
  )

data
#> # A tibble: 1 x 9
#>   id_loan loan_size_outst… loan_size_credi… id_2dii level score sector name_ald
#>   <chr>              <int>            <int> <chr>   <chr> <int> <chr>  <chr>   
#> 1 L1                     1                2 UP1     ulti…     1 power  a power…
#> # … with 1 more variable: sector_ald <chr>


ald <- tibble::tribble(
      ~name_company, ~sector,     ~technology, ~year, ~production, ~emission_factor, ~plant_location, ~is_ultimate_owner,
  "a power company", "power",      "hydrocap", 2020L,          1L,               1L,            "ES",               TRUE,
  "a power company", "power", "renewablescap", 2020L,          1L,               1L,            "ES",               TRUE,
  "a power company", "power", "renewablescap", 2020L,          1L,               1L,            "KZ",               TRUE
  )

ald
#> # A tibble: 3 x 8
#>   name_company sector technology  year production emission_factor plant_location
#>   <chr>        <chr>  <chr>      <int>      <int>           <int> <chr>         
#> 1 a power com… power  hydrocap    2020          1               1 ES            
#> 2 a power com… power  renewable…  2020          1               1 ES            
#> 3 a power com… power  renewable…  2020          1               1 KZ            
#> # … with 1 more variable: is_ultimate_owner <lgl>

scenario <- tibble::tribble(
  ~scenario, ~sector,     ~technology,   ~region, ~year, ~tmsr, ~smsp, ~scenario_source,
      "sds", "power",      "hydrocap",  "europe", 2020L,    1L,    0L,      "demo_2020",
      "sds", "power", "renewablescap",  "europe", 2020L,    1L,    0L,      "demo_2020",
      "sds", "power",      "hydrocap", "caspian", 2020L,    1L,    0L,      "demo_2020",
      "sds", "power", "renewablescap", "caspian", 2020L,    1L,    0L,      "demo_2020"
  )

scenario
#> # A tibble: 4 x 8
#>   scenario sector technology    region   year  tmsr  smsp scenario_source
#>   <chr>    <chr>  <chr>         <chr>   <int> <int> <int> <chr>          
#> 1 sds      power  hydrocap      europe   2020     1     0 demo_2020      
#> 2 sds      power  renewablescap europe   2020     1     0 demo_2020      
#> 3 sds      power  hydrocap      caspian  2020     1     0 demo_2020      
#> 4 sds      power  renewablescap caspian  2020     1     0 demo_2020

loanbook_joined_to_ald <- r2dii.analysis:::join_ald_scenario(data, ald, scenario, region_isos_demo)

loanbook_joined_to_ald %>% r2dii.analysis:::summarize_weighted_production(scenario,
                                                         tmsr,
                                                         smsp,
                                                         region,
                                                         scenario_source)
#> # A tibble: 3 x 9
#>   sector technology  year scenario  tmsr  smsp region scenario_source
#>   <chr>  <chr>      <int> <chr>    <int> <int> <chr>  <chr>          
#> 1 power  hydrocap    2020 sds          1     0 europe demo_2020      
#> 2 power  renewable…  2020 sds          1     0 caspi… demo_2020      
#> 3 power  renewable…  2020 sds          1     0 europe demo_2020      
#> # … with 1 more variable: weighted_production <dbl>
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jdhoffa** [comment]
P.S. make sure you have the most up to date analysis package! As always, we are updating it daily until we release on CRAn, so you may already be using stale code: 
```r
devtools::install_github("2DegreesInvesting/r2dii.analysis") 
```

**Comment by QianFeng2020** [comment]
Hi Jackson, after I updated the package, there is no such error anymore. Thanks!

Qian Feng

**Comment by jdhoffa** [comment]
Great! Thanks Qian :)
Closing the issue now.

**Comment by QianFeng2020** [comment]
Hi Jackson, 

I just found that I did not delete completely my code to make it work.  Another factor to this unique "id" problem is "currency", which I think you can solve in the same way as you do for "location" and "technology".  What I did is to change the id into "id+currency". 

Regards
Qian

**Comment by jdhoffa** [comment]
ah interesting. 
It would actually be best, if possible, to ensure all loans are converted to the same currency prior to running the analysis, otherwise the weightings won't be comparable
