### ISSUE TITLE
Vincent's feedback

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#115]
@jdhoffa, I bring here the feedback that @vintented shared at https://2degreesinvesting.github.io/posts/2020-06-11-r2dii-analysis-release-candidate/

### Vincent 

1. Could be more explicitly that you have to install all 2DII packages and not just analysis.

2. Scenario naming will cause confusion about the source, e.g. automotive should be RTS, SDS, B2DS….

3. Match function: For match function why is name_ald lower case?

4. SDA function: Would be nice if you could group at the company level and not only portfolio level?

---

### Mauro

1. So far we did not ask people to install other r2dii.packages because -- strictly speaking -- r2dii.analysis does not depend in other r2dii packages. The examples use r2dii.data and r2dii.match, but the package r2dii.analysis itself does not need them. This is very confusing and your comment reminds me that we should consider explain this somewhere. Thanks!

2. Jackson should be more able to act on your second general point. Thanks!

3. I'm not 100% sure what function you refer to but in general we favor lowercase names because we follow the tidyverse style guide: https://style.tidyverse.org....

4. Thanks! I'll discuss with Jackson.

**Comment by jdhoffa** [comment]
I have extracted an actionable issue. 
@maurolepore I think we can address the "install the rest of the r2dii packages" in:
1st - the Rmarkdown file outlining the workflow (#107)
2nd - a blog post
3rd - the `r2dii.banks` package when it is ready. 

Are you ok to close this, and address the problems in their appropriate issues?

**Comment by maurolepore** [comment]
Sure.
