### ISSUE TITLE
target_year defaults to latest year in selected market-ref_sectors

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#13]
https://github.com/2DegreesInvesting/r2dii.analysis/pull/10#issuecomment-567877917

> Target year should be an input, in case no target year is given you can use the latest year existing for all ref_sectors selected in the market file. If it solely takes the last year existing it causes the function to fail for the other sectors that do not have values for this year.

**Comment by jdhoffa** [comment]
Closed by #70
