### ISSUE TITLE
Make internal dataset `pick_tmsr_or_smsp` more transparent

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#135]
The purpose of this dataset is to achieve the following logic: 
- IF `technology` is "green" THEN pick `smsp`
- IF `technology` is "brown" THEN pick `tmsr`

I thought this would only be useful in one function, so I skipped the "green" and "brown" part, and just wrote the bridge directly to `smsp` or `tmsr`, but it now looks like it might be good to keep track of which technologies are green or brown directly. 

---

``` r
library(r2dii.analysis)

r2dii.analysis:::pick_tmsr_or_smsp
#> # A tibble: 13 x 3
#>    sector      technology    which_metric                   
#>    <chr>       <chr>         <chr>                          
#>  1 automotive  electric      smsp_target_weighted_production
#>  2 automotive  hybrid        smsp_target_weighted_production
#>  3 automotive  ice           tmsr_target_weighted_production
#>  4 automotive  fuelcell      smsp_target_weighted_production
#>  5 power       hydrocap      smsp_target_weighted_production
#>  6 power       renewablescap smsp_target_weighted_production
#>  7 power       coalcap       tmsr_target_weighted_production
#>  8 power       gascap        tmsr_target_weighted_production
#>  9 power       oilcap        tmsr_target_weighted_production
#> 10 power       nuclearcap    smsp_target_weighted_production
#> 11 oil and gas oil           tmsr_target_weighted_production
#> 12 oil and gas gas           tmsr_target_weighted_production
#> 13 coal        coal          tmsr_target_weighted_production
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
Keeping this dataset internal suggests users should generally be uninterested in it, for example, so as to not need a helpfile documenting it. @jdhoffa is this the case?

**Comment by jdhoffa** [comment]
This is the case. These datasets should essentially only be interesting to 2dii internals.
