### ISSUE TITLE
All functions that require `loan_size_*` should check if input data has identical currency

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#137]
All "loan-weighting" functions (ie. `summarize_*`) assume that the input currency of `loanbook` is consistent (identical across all loans). It doesn't matter what the actual currency is, so long as it's the same across all loans. 

We should write a check for this at the beginning of all functions that have `loan_size_*` as a crucial column, and the functions should error if currencies are not identical. 

Thanks @QianFeng2020

**Comment by QianFeng2020** [comment]
Hi Jackson, 

I talked to Marc and it turns out that all the loan size values are measured in EUR though being marked with different currencies. So this is not a problem for Terra anymore...

Regards
Qian

**Comment by jdhoffa** [comment]
Great!
Even so I will add this check to the code, as other banks will likely run into similar issues

**Comment by jdhoffa** [comment]
Same goes for all functions using `emission_factor` should check that units are consistent, and all functions using `production` should check that units are consistent
