### ISSUE TITLE
"fossil fuel" sector is not included in the result

### ISSUE THREAD

**Issue by QianFeng2020** [2DegreesInvesting/r2dii.analysis#138]
Hey, 

After running the "target_market_share" function, the generated results don't provide outcomes for "fossil fuel" sector and only for "automotive" and "power". 

Thanks! 
Qian

**Comment by jdhoffa** [comment]
@QianFeng2020 quick question: 
Are the "sector" values for the input `ald` and `scenario` file consistent? In particular, I have noticed that sometimes for "fossil fuels" the sector is given as "oil and gas" or "coal". 

If this is the case, you can just edit the ald & scenario files, and whenever sector = "oil and gas" OR "coal" set it to "fossil fuels", and the code should work

**Comment by QianFeng2020** [comment]
Hi Jackson, 

I checked the source code of the "target_market_share" function, and it calls a function "pick_tmsr_or_smsp" which defines technology and metrics for each sector. The data it introduces does not contain the "fossil fuels" sector, but "oil and gas" and "coal" sectors. I assume that adding "fossil fuels" sectors in this function can fix this problem. 

Regards
Qian

**Comment by jdhoffa** [comment]
Good catch! This is actually taken care of in r2dii.data, so I will move the issue over to there. 
Thank you

**Comment by maurolepore** [comment]
Thanks both. Jackson, I'll close this issue here as it now duplicates https://github.com/2DegreesInvesting/r2dii.data/issues/123.

BTW, I think we can achieve the same in one step via the "Transfer issue" feature.

![image](https://user-images.githubusercontent.com/5856545/88189475-b5c5eb00-cbfe-11ea-830f-d64f8b8f950f.png)

**Comment by jdhoffa** [comment]
Very cool
