### ISSUE TITLE
the SDA target results seems strange

### ISSUE THREAD

**Issue by QianFeng2020** [2DegreesInvesting/r2dii.analysis#139]
Hey Jackson, 

I checked the generated outcomes by running the function "target_sda" for "steel sector", but the "projected" values seem strange: It is much higher than any of the CO2 emission factor values of matched companies. My understanding is that the projected value is loan-size weight averaged CO2 emission factor values of matched companies so it should be something between the min and max values. 

Thanks! 
Qian

**Comment by jdhoffa** [comment]
@jdhoffa 
Note to self: this is likely because, while internally the adjusted SDA scenario is applied to the portfolio, the output scenario is still the original SDA scenario. 

TODO: Ensure that the output scenario is g*EF_scen

**Comment by jdhoffa** [comment]
Moving this issue to #148
