### ISSUE TITLE
Add link to online version of SDA documentation

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#14]
@georgeharris2deg, thanks a lot for following up on this issue. I created a separate issue so we don't forget if we close #10.

Summary.

* @2diiKlaus asked for the online version of the SDA documentation, and suspected it's not yet ready.
* @georgeharris2deg shared files with a draft of such documentation and confirmed that it is not yet ready (https://github.com/2DegreesInvesting/r2dii.analysis/pull/8#issuecomment-571108308):

![](https://i.imgur.com/dvMrxRF.png)

TODO:

@georgeharris2deg, whenever you have a link to online version of SDA documentation, please add it as a comment below (not a file, just a link to something public and online).

**Comment by jdhoffa** [comment]
There is now a vignette, which has equivalent information to the word document shown here by @georgeharris2deg 

Closed by #62
