### ISSUE TITLE
EU Taxonomy PACTA intergration 

### ISSUE THREAD

**Issue by georgeharris2deg** [2DegreesInvesting/r2dii.analysis#17]
The EU taxonomy has set definitions for what is considered a green asset. It would be useful to include output in the PACTA analysis that tells a bank the total % of their assets that are considered green under the EU taxonomy. 

Would be useful to have:
1) a total % of the portfolio considered 'green' 
2) a sector break down % 
3) a line graph visualizing the percentage of green assets over the next 5 years. 
        -  eg based on the company's build-out capacity so a loan to a car company that is increasing 
           EV capacity in 2 years' time would show an increase in % of green assets in the automotive 
           sector break down.  
        - This would have to be based on a linear interpolation where the EU taxonomy has 
          diminishing targets that will be set by them. eg car emissions must = 0 by 2050 but the 
          pathway to this is not defined yet so the targets will change. 

Thresholds are uploaded as threshold_df 

The following code can be used to add a 'green' / 'brown' tag to all assets based on the threshold in threshold_df 
NB - I am not sure of the best data frame to mutate this new variable (EU_taxon) too.   

...... <- ....... %>% mutate(...... = ifelse(as.numeric(ALD.EmissionsFactor) > as.numeric(threshold_df$Threshold), "brown", "green"))

In some cases where there are data gaps in either our emission factors, the EU taxonomy doesn't cover the sector (for example shipping or aviation) or there is a miss-match between technologies the taxonomy uses and 2dii report then they will have to be void from the above calculation. 
- I will upload a document laying out these discrepancies. (attached- NB working document)
- threshold_df will be uploaded to r2dii.rawdata (again subject to change pending updates to emission factor data especially units) 

[Eu_Taxon_Documentation.xlsx](https://github.com/2DegreesInvesting/r2dii.analysis/files/4066311/Eu_Taxon_Documentation.xlsx)

**Comment by jdhoffa** [comment]
I think this needs more methodological work for now, and will close this until we have researched it further.
