### ISSUE TITLE
How should we handle NAs in `target_sda`?

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#173]
Due to the nature of the asset-level data, it is a certainty that we will have data for the `production` column for every row, however it is also a certainty that we will be missing data for _some_ `emission_factor`s. This is inevitable as, for certain technologies, it makes sense to calculate `production` but not `emission_factor`s. 

As a brief reminder:
* The function `target_market_share()` is associated with the column `production`
* The function `target_sda()` is associated with the column `emission_factor`

Both functions error if they encounter `NA`s. With all that said, the current workflow is:

1. calculate `target_market_share` targets using the _full_ ALD 

2. subsequently have the user filter out `NA`s from `emission_factor` prior to using `target_sda`

I think unfortunately this workflow won't work in practice, as people may accidentally use the "filtered" ALD for _both_ functions, and will end up missing some crucial values. 

@maurolepore what are your thoughts on this?

**Comment by maurolepore** [comment]
Can we drop `NA`s from `emission_factor` inside `target_sda()`? If so, users would always input the _full_ ald; an we drop `NA`s for them (maybe with a warning) only where it's relevant.

**Comment by jdhoffa** [comment]
I think this is the approach we should take. I'll do so today!
