### ISSUE TITLE
Issue of visibility with dev magrittr

### ISSUE THREAD

**Issue by lionel-** [2DegreesInvesting/r2dii.analysis#188]
Hello,

I'm working on the new magrittr version which switches to a lazy evaluation model. I'm seeing this failure:

```
  > test_check("r2dii.analysis")
  ── 1. Failure: returns visibly (@test-join_ald_scenario.R#17)  ─────────────────
  join_ald_scenario(...) does not invisibly
```

Because the pipe is now lazy, `1 %>% identity() %>% invisible()` is now equivalent to `identity(invisible(1))`, which returns invisibly. A simple fix would be to save the result of the pipe to a variable and return that variable, e.g. `foo <- invisible(1); foo`. We're planning to release in one month. It would be great if you could update your package before then :)

**Comment by jdhoffa** [comment]
Thanks for the heads up @lionel- , on it now!
