### ISSUE TITLE
Test expected behaviour of sda_portfolio_target()

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#20]
@vintented,

We need to test what we expect from `sda_portfolio_target()`. Currently almost all tests just check for bad inputs (e.g. equivalent to testing that `sum("a", "b")` throws an error), and that the function is sensitive to its arguments (e.g. that `sum(1, NA, na.rm = TRUE)` is different than `sum(1, NA)`). But -- except the last test -- we have no test about the actual work the function does (e.g. that `sum(1, 1)` returns `2`).

Can you design such tests?

* Work with the minimum data possible (e.g. 1, 2 rows and as few columns as possible).
* Test common cases.
* Test edge cases (e.g. impossible years).

--

![](https://i.imgur.com/bL1petf.png)

**Comment by jdhoffa** [comment]
Superseded by #62
