### ISSUE TITLE
SDA / Market Share Approach links swapped

### ISSUE THREAD

**Issue by apmanning** [2DegreesInvesting/r2dii.analysis#222]
Under the _Calculate targets_ section on https://2degreesinvesting.github.io/r2dii.analysis/articles/r2dii-analysis.html , the links to https://2degreesinvesting.github.io/r2dii.analysis/articles/target-market-share.html and https://2degreesinvesting.github.io/r2dii.analysis/articles/target-sda.html go to the wrong pages.

**Comment by jdhoffa** [comment]
Thanks for flagging this @apmanning! Should be fixed now.
