### ISSUE TITLE
Are these differences expected?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#227]
The intended release of r2dii.data 0.1.5 exposed problems with reverse dependencies: r2dii.match and r2dii.analysis. 
The problems in r2dii.match seems related to changes in the column `borderline` 

``` r
subset(
  r2dii.data::data_dictionary, 
  subset = column == "borderline", 
  select = c("dataset", "column")
)
#>                   dataset     column
#> 14     cnb_classification borderline
#> 30    gics_classification borderline
#> 38    isic_classification borderline
#> 63    nace_classification borderline
#> 68   naics_classification borderline
#> 91 sector_classifications borderline
#> 95     sic_classification borderline
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Here I see many differences and I need help to decide if updating the regression references is the right thing to do.

![image](https://user-images.githubusercontent.com/5856545/99716809-2e826a00-2a6e-11eb-9139-20348c27cae7.png)

![image](https://user-images.githubusercontent.com/5856545/99716869-3fcb7680-2a6e-11eb-8e24-1cdf6ba525a5.png)

![image](https://user-images.githubusercontent.com/5856545/99716918-4c4fcf00-2a6e-11eb-8500-4454c59d9428.png)

![image](https://user-images.githubusercontent.com/5856545/99716949-55d93700-2a6e-11eb-8ecc-b0509234a7c0.png)

**Comment by maurolepore** [comment]
@jdhoffa please comment.

**Comment by jdhoffa** [comment]
The cause for these differences is not immediately clear to me, and somewhat unexpected. I will explore and open a PR if I figure anything out
