### ISSUE TITLE
Multiple "projected" results based on different "scenario_scource"

### ISSUE THREAD

**Issue by georgeharris2deg** [2DegreesInvesting/r2dii.analysis#229]
When running r2dii.analysis::target_market_share with a scenario file that contains multiple scenario_source's (e.g. WEO and ETP) the resulting projected column is duplicated and different.  

A quick fix is to edit the scenario file to only contain the scenario_soucres that are needed for the analysis and to run the analysis by sector. 
For example
_Auto_results <- taregt_market_share(lbk_ready_auto, ald, scenario_auto)_

Whereby scenario_auto only contains one scenario_source - in this case scenarios from the ETP. 

Perhaps a more long term solution could be one meta scenario file containing all scenario sources and sectors - then an additional argument could be added to the target_market_share function allowing a user to pick the scenario source. 
- personally, I think we should move away from this as it ties the scenario files to the one (in this case meta file) that 2dii creates. In the future, I think we should move to a series of one of the scenario files that can be created and made openly available by third parties - this way there can be an only repo of scenarios files than users can pick and choose from to use in their PACTA analysis. 
- This is open for discussion

the file that causes the error 
[scenario_2020_FF_Power_Auto (2).xlsx](https://github.com/2DegreesInvesting/r2dii.analysis/files/5596055/scenario_2020_FF_Power_Auto.2.xlsx)

A stripped-down version that causes no error 
[Scenario_Auto.xlsx](https://github.com/2DegreesInvesting/r2dii.analysis/files/5596051/Scenario_Auto.xlsx)

**Comment by jdhoffa** [comment]
Hey @georgeharris2deg, I just realized that we actually need to have different projected outputs by scenario source+region. 

Why? Different scenario sources define regions differently, this is why the `region_isos` dataset is necessary. 

E.g. consider if WEO2019 defines the EU as containing the UK, and WEO2020 doesn't. If you filter for the region EU, AND the portfolio has exposure to UK companies, then this `projected` value should be different in each case. 

That said, I think what this issue is identifying, is that the `projected` output should be identical for all scenario sources, when `region == "global"`, and I believe this is still a bug. 

Does this make sense, and have I identified well the issue that you see?

**Comment by georgeharris2deg** [comment]
I see - thanks 

This does make sense - In which case I think we should make this more obvious to avoid any future confusion. 
I can add a note on the TM website stating that the projected will vary depending on the regional benchmark wich, in turn, may be defined differently by scenario source. 

Is there anywhere in the code universe that you can add something similar - may be on the websites or even in the data dictionary? - 

Perhaps even better we create an article for interpreting the results and describe this here - this is then published on the r2dii.analysis website - let me know if you like this idea and we can find some time to draft this 

Thanks

**Comment by jdhoffa** [comment]
I am not sure where the best place for this to live is right now, so I will extract this as a separate issue, and also think we should discuss overall "results interpretation" as a separate matter/ try to time it with the `r2dii.analysis` webinar. 

Lets discuss in the banks committee, and I can also chat with Mauro and see where he thinks it could live in the code

**Comment by jdhoffa** [comment]
@georgeharris2deg closing, as I believe this is resolved in the above conversation.
