### ISSUE TITLE
Is this dead code?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#232]
We seem to no longer need inst/extdata/valid_matches.csv -- apparently since 1b2a2295e1bd04c843cb0659f921c0ccbbffda2e.

Can we remove these two files?:

* https://github.com/2DegreesInvesting/r2dii.analysis/tree/master/inst/extdata/valid_matches.csv
* https://github.com/2DegreesInvesting/r2dii.analysis/blob/master/data-raw/valid_matches.R

**Comment by jdhoffa** [comment]
Yup I agree!
