### ISSUE TITLE
ALD and Portfolio level results not matching

### ISSUE THREAD

**Issue by lucasreiscorreia** [2DegreesInvesting/r2dii.analysis#257]
Hi Guys,

As I've talked to George, we ran portfolio level results with the target share function (and sd for steel and cement). They work perfectly well and match for Power and Steel. However, filtering as we should, we are getting substantial differences between our results comparing to ALD for Automotive; Oil&Gas; Cement and Coal.

Thanks,
Lucas

**Comment by maurolepore** [comment]
Hi Lucas, 

Thanks for your feedback!

It will help a lot to have some more detail. If you can recreate your problem with toy public data (not private), it would be great to share a reproducible example with the reprex package (https://reprex.tidyverse.org/), explaining what you expected and showing what you got.

If not, I'm afraid we'll have to pick your brain via a call or more messages -- once we are all back to work in 2021.

**Comment by jdhoffa** [comment]
Closing this, as we will need more context to be able to address it.
