### ISSUE TITLE
See why check fails with r2dii-devel on ubuntu 16.04 and R-release

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#276]
https://github.com/2DegreesInvesting/r2dii.analysis/pull/275#issuecomment-765369148

I would let this sit for a bit. The issue seems minor and it may be fixed by itself -- so may not be worth the effort.

**Comment by jdhoffa** [comment]
I think it has fixed itself, so I will close this issue.
