### ISSUE TITLE
Align how `target_market_share` and `target_sda` handle input `NA`s

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#304]
Currently `target_market_share` will fail if a crucial column (e.g. `production`) has `NA` values,  while `target_sda` allows for `NA`s to be input, however it automatically filters them out. 

This decision for `target_sda` to handle `NA`s in this way was made since the input dataset provided by AR to the banks WILL automatically have `NA`s in the `emission_factor` column since certain sectors have no `emission_factors`. Rather than having the users filter a dataset provided by "us", we thought it would be good for the software to work "out of the box" with the data provided, but it might be worth revisiting this decision. 

As a user, it could be nice for both of these functions to handle `NA`s in the same way. 

See reprex below (and notice that `target_market_share` ERRORS, while `target_sda` WARNS): 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)
library(r2dii.analysis)

matched <- tibble::tribble(
  ~id_loan, ~loan_size_outstanding, ~loan_size_outstanding_currency, ~loan_size_credit_limit, ~loan_size_credit_limit_currency, ~id_2dii,            ~level, ~score,      ~sector,      ~name_ald,  ~sector_ald,
  "L162",                      1,                           "EUR",                       2,                            "EUR",    "UP1", "ultimate_parent",      1, "automotive", "shaanxi auto", "automotive"
)

ald <- tibble::tribble(
  ~name_company,      ~sector, ~technology, ~year, ~production, ~emission_factor, ~plant_location, ~is_ultimate_owner,
  "shaanxi auto", "automotive",       "ice",  2025,           1,                1,            "BF",               TRUE,
  "shaanxi auto", "automotive",       "ice",  2025,           NA,                NA,            "BF",               TRUE
)


target_market_share(
  matched, 
  ald,
  scenario_demo_2020,
  region_isos_demo
)
#> Error: Column `production` must not contain any `NA`s.

target_sda(
  matched,
  ald,
  co2_intensity_scenario_demo,
)
#> Warning: Removing ald rows where `emission_factor` is NA
#> Warning: Found no scenario data for input ald.
#> # A tibble: 0 x 4
#> # … with 4 variables: sector <chr>, year <int>, emission_factor_metric <chr>,
#> #   emission_factor_value <dbl>
```

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maurolepore** [comment]
> As a user, it could be nice for both of these functions to handle NAs in the same way.

I agree we should be consistent. I didn't quite get if you prefer both to (a) exclude `NA`s with a warning, or (b) throw an error.

**Comment by jdhoffa** [comment]
I am actually not sure!! I just wanted to get the discussion into an issue, but I see benefits to either option. 
- option a) allows the user to directly use the ALD we provide, and they wouldn't be receiving a dataset that they then have to mess around with before using
- option b) is safer, and forces the user to be sure of what they are doing/ trying to do

Maybe we include @georgeharris2deg in this discussion as an external view to vote for the better option? I **might** lean towards option a) just to ensure the package remains usable with minimal effort, but I worry this could cause silent issues later down the road.

**Comment by maurolepore** [comment]
OK, let's see what George says. I also lean towards removing `NA` with a warning. It's not uncommon (e.g. ggplot does it extensivley) and less disruptive for users that may already have written working scripts that would otherwise start to fail. If we wanted to pass control to the users, then we could either add an argument `na.rm` or an option like `r2dii.analysis.na.action = c("warning", "error")`.

**Comment by jdhoffa** [comment]
Ok, if you're happy with that solution then I back it too!
