### ISSUE TITLE
Plotting the corp economy for green technologies issue 

### ISSUE THREAD

**Issue by georgeharris2deg** [2DegreesInvesting/r2dii.analysis#316]
The corporate economy is not plotted consistently between different scenarios when the portfolio changes. 
This is not the case for brown technologies. 
attached is an excel that proves this 

to be discussed with @Antoine-Lalechere @georgeharris2deg @MonikaFu @jdhoffa 
[corp econ_ gren tech issue .xlsx](https://github.com/2DegreesInvesting/r2dii.analysis/files/6688285/corp.econ_.gren.tech.issue.xlsx)

**Comment by jdhoffa** [comment]
@georgeharris2deg this issue is already open here: #269 
I will move the message and excel sheet to that issue and close this.
