### ISSUE TITLE
Coal share increasing

### ISSUE THREAD

**Issue by Antoine-Lalechere** [2DegreesInvesting/r2dii.analysis#317]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/>, <https://community.rstudio.com/> or email Mauro Lepore at <mauro@2degrees-investing.org>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
CoalCap share in the techmix of the reprex is increasing which is weird as it is supposed to be constant. Also, coal share appears to be 0.66 and I am assuming it should be a bit lower

```r
# insert reprex here



matched <-loanbook_demo %>% 
  match_name(ald) %>% 
  prioritize() %>%
  filter (
    sector_ald=="power",
    name_ald=="dynegy midwest generation, inc." | name_ald=="noshiro forest resources utilization cooperative association" 
  )

out <- matched %>% 
  target_market_share(
    ald, 
    scenario_demo_2020,
    region_isos_demo
  ) %>% 
  filter(
    metric=="target_sds",
    by_company=TRUE
  )

```

**Comment by jdhoffa** [comment]
@Antoine-Lalechere thanks for flagging this! Just FYI this issue is already open at #315 

I will make a reprex with the added context here, add it to that issue, and close this one.
