### ISSUE TITLE
Update the 'Get started' with `r2dii.plot` visualisation examples?

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.analysis#321]
Currently generic ggplot plots are shown but it might be nice to show some examples from `r2dii.plot`. We might want to keep 1 example of a generic `ggplot` as well.

**Comment by jdhoffa** [comment]
Reopening as @MonikaFu mentions that using `r2dii.plot::qplot_trajectory()` might look better.
