### ISSUE TITLE
Prefer  `[` to `$` as  an accessor (`.data["sector_ald"]`).

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#335]
Non-blocking: prefer  `[` to `$` as  an accessor (`.data["sector_ald"]`). 

_Originally posted by @AlexAxthelm in https://github.com/2DegreesInvesting/r2dii.analysis/pull/330#discussion_r665677324_

**Comment by maurolepore** [comment]
Why is `df$column` better than `df[["column"]]`?

--

Notice that `$` is equivalent to `[[` not `[`.

``` r
identical(mtcars$cyl, mtcars[["cyl"]])
#> [1] TRUE
identical(mtcars$cyl, mtcars["cyl"])
#> [1] FALSE
```

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by AlexAxthelm** [comment]
> This accessor is handiest when doing interactive programming but should be discouraged for more production oriented code because of its limitations, namely the inability to interpolate the names or use integer indices.

https://www.r-bloggers.com/2009/10/r-accessors-explained/

The cleanest example that I can think of is passing a variable column name (or number) in for selection, rather than hardcoding
```r
df <- data.frame(foo = 1:3, bar = 4:6)
blah <- ifelse(runif(1) > 0.5, "foo", "bar")
df$blah #returns NULL
df[[blah]] # returns either 1:3 or 4:6
```

**Comment by maurolepore** [comment]
Thanks for explaining. For completeness, the relevant piece in `?Extract` seems to be this:

`?Extract`
> Both [[ and $ select a single element of the list. The main difference is
> that $ does not allow computed indices, whereas [[ does. x$name is equivalent 
> to x[["name", exact = FALSE]]. Also, the partial matching behavior of [[ can 
> be controlled using the exact argument.

So far we default to `$` unless we need to compute indices, for example to select the columns that don't match a specific string:

``` r
df <- data.frame(foo = "foo", bar = "bar")
df$bar  # I know which colum I want
#> [1] "bar"
df[[setdiff(names(df), "foo")]]  # I compute the columns I want
#> [1] "bar"
```

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

--

It's your call Alex. If this is important I'm happy to follow your advice. Which approach would you choose?:

1. Default to `[[` in new code.
2. Change`$` to `[[` in this package.
3. Chage `$` to `[[` in all packages.
4. Something else?

**Comment by AlexAxthelm** [comment]
My inclination is that we would start using `[[` in new code, or when we touch old code we change it (as a general pattern, across packages), but this should prbably be something that we discuss when we're establishing a style guid

**Comment by jdhoffa** [comment]
I will close this issue, since it pertains mostly to the style-guide/ general advice for new code, and isn't a direct issue in this repo.
