### ISSUE TITLE
Upgrade to r-lib v2 Actions

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.analysis#387]
Official v2 example actions here: https://github.com/r-lib/actions/tree/v2-branch/examples

https://github.com/2DegreesInvesting/r2dii.analysis/blob/a54247b7db9f33e8e2bdd7662e7afce5bbdd1244/.github/workflows/check-full.yaml#L46-L58

https://github.com/2DegreesInvesting/r2dii.analysis/blob/a54247b7db9f33e8e2bdd7662e7afce5bbdd1244/.github/workflows/check-full_r2dii-devel.yaml#L46-L64

https://github.com/2DegreesInvesting/r2dii.analysis/blob/a54247b7db9f33e8e2bdd7662e7afce5bbdd1244/.github/workflows/pkgdown.yaml#L18-L24

https://github.com/2DegreesInvesting/r2dii.analysis/blob/a54247b7db9f33e8e2bdd7662e7afce5bbdd1244/.github/workflows/pr-commands.yaml#L14-L53

https://github.com/2DegreesInvesting/r2dii.analysis/blob/a54247b7db9f33e8e2bdd7662e7afce5bbdd1244/.github/workflows/render-readme.yaml#L19-L20

https://github.com/2DegreesInvesting/r2dii.analysis/blob/a54247b7db9f33e8e2bdd7662e7afce5bbdd1244/.github/workflows/test-coverage.yaml#L20-L24

**Comment by jdhoffa** [comment]
While updating the workflows, I notice this output from `usethis`:
``` r
> usethis::use_github_action_check_full(save_as = "check-full")
Error: `use_github_action_check_full()` was deprecated in usethis 2.1.0 and is now defunct.
It is overkill for the vast majority of R packages.
The "check-full" workflow is among those configured by `use_tidy_github_actions()`.
If you really want it, request it by name with `use_github_action()`.
```

based on this, I'm considering if the r2dii-verse really needs the rigor of the `check-full` checks. 
@maurolepore @cjyetman any thoughts?

**Comment by cjyetman** [comment]
I agree, it's overkill.
