### ISSUE TITLE
Overview of where we stand (2020-03-11)

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#39]
> Can you (together with Jackson) prepare an overview of where we stand in the r2dii.analysis library for me to get a good overview of where we are and what is still needed for next weeks catch-up?
-- @2diiKlaus 

Here is my view. @jdhoffa can you comment?

The precise roadmap to achieve a minimum viable product is still a bit unclear to me, but Jackson suggested we need only a few features. He contributed some features and explained how I could move forward on my own while he focuses on a different project. This seems doable but likely less effective compared to working with more input from Jackson. So instead I now prefer to strengthen the foundations of this package before I build more stuff on wobbly ground. 

r2dii.analysis builds on r2dii.data and r2dii.match. Those packages are still unreleased but we have enough feedback to release them. r2dii.data is ready to submit to CRAN, except I would like Jackson to double-check that all data is public and the license is okay. r2dii.match needs to wait until r2dii.data is published.

Back to r2dii.analysis, this is what we have:

FEATURES

Both Vincent and Jackson contributed features. See https://2degreesinvesting.github.io/r2dii.analysis/reference.

* `sda_portfolio_target()` (Vincent):  Calculate portfolio targets using the Sectoral Decarbonisation
       Approach (SDA)
* `join_ald_scenario()` (Jackson): Join a data-loanbook object to the ald and scenario
*  `add_fair_share_columns()`: Add "fair share" columns to a scenario dataset

ARTICLES

Jackson contributed two articles (see https://2degreesinvesting.github.io/r2dii.analysis/article)

* Bank Workflow
* Scenario Fair Shares

WIP 

Pull requests:
* (#34) `summarize_weighted_production()` Needs some more tests
* (#11) Single indicator & InfluenceMap weighting methodology. Needs technical work and tests.

PLANS

Implement equations in `add_fair_share_coulmns()`

**Comment by jdhoffa** [comment]
Old issue
