### ISSUE TITLE
Deprecate references to ALD in favour of ABCD

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#404]
See this brief blog post explaining the decision: https://2degreesinvesting.github.io/posts/2022-03-02-ald-becomes-abcd/

In r2dii.analysis, the key changes in the API will be:
- `target_market_share(..., ald)`, `target_sda(..., ald)` need to be depracated -> `target_market_share(..., abcd)`, `target_sda(..., abcd)`
- `join_ald_scenario` will need to be superseded by `join_abcd_scenario` ( think this function could just be deprecated entirely..., maybe a discussion for @AlexAxthelm @cjyetman @maurolepore )

In documentation:
- All references to ald_demo should now reference abcd_demo (needs to wait for [this PR](https://github.com/2DegreesInvesting/r2dii.data/pull/280) to be merged and pushed to CRAN).

**Comment by jdhoffa** [comment]
@AlexAxthelm would also like some feedback here as to if it makes sense to simply deprecate `join_ald_scenario` entirely (without replacing it with anything). If you agree, I would like to put out a warning that we are doing so in this release

**Comment by AlexAxthelm** [comment]
The Idea here being that users would do this joining themselves?

**Comment by jdhoffa** [comment]
To run `target_market_share` and `target_sda` they don't need to (`join_ald_scenario` is called internally by both functions). This function was exported just as a sort of utility function, but seeing as it is just a couple of joins, I think it is fine for users to do it themselves if they want.
