### ISSUE TITLE
Remove the `add_*()` prefix where output does not preserve original columns

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#67]
The `add_*()` functions here do not preserve the original columns

![image](https://user-images.githubusercontent.com/5856545/83146851-770f2b00-a0bc-11ea-80a4-e79241ab541a.png)

In dplyr, `add_count()` and `add_tally()` preserve the original columns and add a new one -- which  differentiates these functions from their summary counterparts `count()` and `tally()`. I like the idea of reserving the prefix "add_" to communicate that the output will have the same columns that the input has (plus something else).

Is this something we want here too?

``` r
library(dplyr, warn.conflicts = FALSE)

# In dplyr, summary functions don't preserve columns
# Original
mtcars %>% ncol()
#> [1] 11
# Summary
mtcars %>% count(cyl) %>% ncol()
#> [1] 2
mtcars %>% group_by(cyl) %>% summarize(n = n()) %>% ncol()
#> [1] 2

# But functions with the prefix "add_" preserve original columns
mtcars %>% ncol()
#> [1] 11
# Same columns plus one
mtcars %>% add_count(cyl) %>% ncol()
#> [1] 12
```

<sup>Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jdhoffa** [comment]
I like this idea. For now, let's just call these functions `portfolio_target` and `sda_target`, as I think the summary results are more useful/ easier understood by the audience at this stage. and we can add the add_* functions later, what do you think?

**Comment by jdhoffa** [comment]
we also might consider renaming `add_portfolio_target` and `add_company_target` to `portfolio_production_target` and `company_production_target` to better distinguish from `sda_target`.

**Comment by maurolepore** [comment]
How about excluding "production", in the same way `sda_target()` excludes "emission-factor"?

So the suite would be:

* `sda_target()`
* `portfolio_target()`
* `company_target()`

And if we go that route, then how about using `target_` as a prefix, so they are easier to find with tab-complete. So:

* `target_sda()`
* `target_portfolio()`
* `target_company()`

**Comment by jdhoffa** [comment]
I propose calling the functions: 
* `target_sda()`
* `target_fair_share_portfolio()`
* `target_fair_share_company()`

we may also consider splitting `target_sda` into `target_sda_portofolio()` and `target_sda_company()` (i only summarized at portfolio level because thats what i think is most useful, but we can easily include both for symmetry). 

This also connects the functions easily to the relevant pkgdown articles.

**Comment by maurolepore** [comment]
Cool. I like your idea of making the functions behave in a similar way. That helps users port what they learn from one function to the other because they know what to expect. 

How useful is the "target" prefix? Can we drop it and rely on `@family target functions` to link all these functions in `@seelaso` and under the same section of the website's Reference?

**Comment by jdhoffa** [comment]
Hmm, having the function just called `sda()` seems not to explain it's functionality enough/ might confuse users, I'm not sure... Agreed it seems like a waste to have target twice, but I'm just trying to think about the users that will never look at the Reference/ function family etc.
