### ISSUE TITLE
Consider moving half of join_ald_scenario() to r2dii.match

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.analysis#80]
The workflow may be simpler if we join `ald` in r2dii.match and join `scenario` in r2dii.analysis. That way we should be able to feed `ald` just once.

**Comment by jdhoffa** [comment]
I just had a realization. In the `target_sda()` function, we also need ald as an input argument, but it is actually used internally twice. Once to "join" to the portfolio, but also another time to calculate a "market benchmark" (which really is an "analysis" task, not a matching task). So in this sense, at least for that particular function, we will be doomed to have `ald` as an argument twice...

**Comment by jdhoffa** [comment]
maybe we can discuss next week

**Comment by maurolepore** [comment]
I think this is no longer an open discussion.
